site_name: Explore MkDocs Material
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.tabs.link
    - search.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: brown
      accent: green
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: brown
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/wmelvin'

copyright: '&copy; 2024 Bill Melvin'
