site_name: Explore MkDocs Material
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.tabs.link
    - search.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: brown
      accent: green
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: brown
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/wmelvin/explore-mkdocs-material'

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: 'Original material &copy; 2024 Bill Melvin'
